project:
  type: book

book:
  title: "AGNR 220"
  subtitle: "Introduction to Statistical Analysis in Agriculture and the Natural Resources"
  author: "Alejandro Molina Moctezuma"
  date: "6/6/2025"
  chapters:
    - index.qmd
    - intro.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: united
  pdf:
    documentclass: scrreprt

editor: visual

