---
title: "Syllabus: AGNR 220 - Introduction to Statistical Analysis in Agriculture and the Natural Resources"
format: html
---

AGNR 220: Introduction to Statistical Analysis in Agriculture and the Natural Resources Cross-listed: SNR 220 3 credits SNR Introduction to Statistical Analysis in Agriculture and the Natural Resources This course will provide students with an overview of statistical methods used in agriculture, animal sciences, plant sciences, and natural resource management and research. Students will familiarize themselves with data collection techniques and experimental design, probability distribution, statistical tests, measures of central tendency and dispersion. Simple linear regression, correlation and linear models.

Satisfies General Education Requirement: Quantitative Reasoning (QR) As this course will be submitted to be considered a Quantitative Reasoning VolCore course. As such, this course will include the following learning outcomes in addition to the ones presented in this syllabus: Quantitative and statistical evidence and mathematical and logical reasoning often play critical roles in building arguments and claims to support opinions and actions. Students should therefore possess the mathematical and quantitative skills needed to evaluate such arguments and claims. Students should be able to recognize the quantitative dimensions of questions and issues they will encounter in their professional and personal lives. They also should be able to use mathematical and logical reasoning to formulate and solve problems. Courses in this area are expected to produce the following learning outcomes for students: 1. Students will demonstrate the ability to identify those aspects of arguments and claims that rely on quantitative evidence and on mathematical or logical reasoning. 2. Students will demonstrate the ability to evaluate the appropriateness of conclusions drawn from quantitative evidence and mathematical or logical reasoning techniques. 3. Students will demonstrate the ability to formulate and solve problems that rely on mathematical or logical reasoning. As such, students taking this course will satisfy those learning outcomes in addition to the specific learning outcomes in this syallbus

Specific Course Objectives This is an applied data analysis course targeted to students working in natural resources and agriculture. This course will focus on real world problems and real world data relevant to natural resources, animal science, plant science, and agriculture. All the applied problems we will work on are from the real-world, and can be solved using real-world data. The ultimate objective is for students to be able to answer and solve data problems commonly found in the natural resources by analyzing data and inferring results. Some of the outcomes for students are to: (1) identify data types, and statistical methods, (2) apply statistical techniques to a variety of natural resource management questions, (3) identify and apply statistical methods commonly used to answer questions in agricultural resource analysis, (4) communicate results of statistical analysis to stakeholders (e.g., users of natural and agricultural resources), (5) apply statistical knowledge to decision making in natural resources and agriculture, and (6) analyze data sets using excel and basic introduction to R. Course Structure This course will be structured in units, each week will represent one unit with specific learning objectives. During each unit, the student will attend lecture: 1. Learning: This will be a theoretical, lecture-based session 2. Practice: We work on an example in the classroom. You can work collaboratively. 3. Real world agricultural/natural resource applications: Problem solving. You are presented with a real-world scenario in which you are tasked with identifying the correct analysis, analyze the data, draw conclusions, and present them to potential stakeholders. 4. Online Readings and Discussions: Supplementary to the classroom lectures 5. Take- home assignment: Based on the real-world example

Course Materials Books: Whitlock and Schluter. 2020. The Analysis of Biological Data. MacMillan Learning. 810 pp. Other recommended -but not required- books include: Bivand, R.S., E. Pebesma, and V. Gómez-Rubio. 2013. Applied spatial data analysis with R. 2nd Ed. Springer. 405 pp. Guy C.S., M.L. Brown. 2007. Analysis and Interpretation of Fisheries Data. American Fisheries Society. 961 pp Lawson, J. 2014. Design and analysis of experiments with R. Chapman & Hall/CRC Texts in Statistical Science. 620 pp. Robinson, A.P. and J.D. Hamann. 2011. Forest analytics with R: an introduction. Springer. 339 pp. Stevens, M.H.H. 2009. A primer of ecology with R. Springer. 388 pp. Wickham, H. and G. Grolemund. 2017. R for Data Science. O’Reilly Media. 522 pp. Those books are recommended based on different interests and are considered advanced. Discussions will be based on different articles on different data analysis topics or specific studies in Agriculture and Natural Resources. All the articles will either be open access, or be available to you for free using your library access. Course Concept Map

The course map represents the knowledge areas (rounded edges) that will inform the content of the course, as well as other courses that will utilize the knowledge obtained in this class in their own teaching. This course concept map will be updated regularly.

Grading:\
Assignments 400 points Take home exam 100 points Mid-terms (2) 200 points Critical Thinking assignments (3) 150 points Final Exam 150 points

Total 1000 points Extra credits: \~25 points \~25 points Grading Scale: A \>914 points \>91.49% A- 900-914 points 90 - 91% B+ 880-899 points 88 - 89% B 820-879 points 82 - 87% B- 800-819 points 80 - 81% C+ 780-799 points 78 - 79% C 720-779 points 72 - 77% C- 700-719 points 70 - 71% D 600-699 points 60 - 69% F \<600 points \<60%

Preliminary Schedule based on a 16-week semester Module Topic Assignment 1 Introduction to course Why do we use data and statistical analyses in Agriculture and Natural Resources? Case Study Readings: Failure to use data to make decisions in Ag and NR. 2 Introduction to statistics, data, and describing data Assignment: a) Sampling biological populations b) Describe data 3 Describing data (central tendency estimates and uncertainty) and plotting Probability Assignment: Presenting data ethically to stakeholders (data assignment) 4 Probability II Assignments: a) Probability assignment 5 Hypothesis testing 1 (Introduction) Critical thinking assignment: “Using Hypothesis testing to make a decision regarding milk production in a farm” 6 Hypothesis testing 2: One-sample and two-sample t-test Introduction to R: Test your knowledge: Assignment on differences in growth in two Tuna species based on the presence of a parasite 7 Biology and the history of statistics Exam 1 8 Signed rank test, rank sum test, permutation test Exam review 9 Comparing means from more than two groups Assignment: exploring multiple groups 10 Designing Experiments 1 Critical thinking assignment: Design an experiment 11 “Ecological Experiments”: Statistical analysis when we can’t control variables Take-home exam 12 What happens when the assumptions aren’t met? Non-parametric tests I Non-parametric assignment 1 13 Non-parametric tests II Non-parametric assignment 2 14 Regression and Correlation Critical thinking assignment: Find correlations 15 Modern statistics used in agriculture and natural resources Multiple factors influence the survival of juvenile bats Week 16: Review, and final exam Assignments and exams description: 1- Assignments and exams. a. The core of all questions in the weekly assignments and tests will be to connect problems, or questions to potential solutions that require multiple quantitative and logical reasoning steps. 2- Take home exam: a. This exam will require students to research a problem and use the quantitative and analytical tools they have been learning in order to solve real-world natural resources management questions. 3- Critical thinking assignments: a. In these assignments, students will be tasked to connect real world problems, quantitative methods, and logical reasoning in order to make recommendations on a potential issue in natural resources. b. Importantly, these assignments will have multiple potential solutions, and you have to think critically about the implications of your recommendations

Due dates and late policy Assignments: Weekly assignments will be due seven days from when they are published. Late policy: I expect students to be on-time with their assignments and papers. However, due to life situations, I understand that some delays are inevitable, and I trust that you are doing your best in completing the assignments. All students are awarded one, seven-day extension, no questions asked, no points deducted. All other late assignments will have points deducted: • -10% (if late up to 7 days) • -25% (if late up to 14 days) • Assignments with over 14 days delay will NOT be accepted All late assignments need to be turned in before the end of the semester (before exam’s week start). Exceptions to late policy: Justified extensions due to sickness or other personal reasons will be considered on a case-to-case basis. Please contact me as soon as possible. Academic integrity: Academic dishonesty of any sort will not be tolerated. Plagiarism includes the copying of answers, phrases, portions of sentences or the main ideas from anyone (including a classmate or friends who had taken the class previously) on any work submitted for a grade. Plagiarism also includes using artificial intelligence software such as ChatGPT to generate answers and text on any submitted work. Email: We will be using Canvas in this class and communicate via email. You are expected to check your UT email account frequently (i.e., at least every other day) to keep up with class assignments and activities.

Changes in the Syllabus: We plan to follow the syllabus as the course has been laid out herein. If we need to update the syllabus and change the plan, you will be notified as to changes in calendar dates, assignments, and grading policy, etc.

University Policies: When you enroll at the University of Tennessee you pledge to hold yourself and your peers to the standards of academic honesty and integrity as described in the Academic Policies and Code of Conduct. You are expected to uphold your pledge to honesty and integrity in this course. Academic dishonesty in any form will not be tolerated. Visit: https://studentconduct.utk.edu/wp-content/uploads/sites/53/2021/08/2m3k1ac-Fall-StudentCodeOfConduct_WEB.pdf to read more about the University of Tennessee Academic Policies and Standards of Conduct, behavior that constitutes academic dishonesty, and sanctions.

Student Disabilities The University of Tennessee, Knoxville, is committed to providing an inclusive learning environment for all students. If you anticipate or experience a barrier in this course due to a chronic health condition, a learning, hearing, neurological, mental health, vision, physical, or other kind of disability, or a temporary injury, you are encouraged to contact Student Disability Services (SDS) at 865-974-6087 or sds\@utk.edu. An SDS Coordinator will meet with you to develop a plan to ensure you have equitable access to this course. If you are already registered with SDS, please contact your instructor to discuss implementing accommodations included in your course access letter.

UT Policy on Use of Artificial Intelligence in the Class In this course, it is expected that all submitted work is produced by the students themselves, whether individually or collaboratively. Students must not seek the assistance of Generative AI Tools like ChatGPT. Use of a Generative AI Tool to complete an assignment constitutes academic dishonesty.

## Summary of course in 2025

This was different from the expectations. I want to change it to the original plan, but this made some sense with how the semester went.

Course Summary: Course Summary Date Details Due Mon Aug 25, 2025 Assignment Reading #1 due by 1:30pm Fri Aug 29, 2025 Assignment Assignment 1 due by 1:30pm Fri Sep 5, 2025 Assignment Assignment 2 due by 11:59pm Mon Sep 8, 2025 Assignment Assignment 3 part 1. due by 11:59pm Fri Sep 12, 2025 Assignment assignment 3 part 2 due by 11:59pm Fri Sep 19, 2025 Assignment Assignment week 4 Critical Thinking due by 11:59pm Mon Sep 22, 2025 Assignment Guide 1 due by 11:59pm Mon Sep 29, 2025 Assignment Hypothesis testing assignment due by 11:59pm Mon Oct 13, 2025 Assignment Critical Thinking Assignment 2 due by 1:50pm Wed Oct 15, 2025 Assignment Chi square due by 2pm Fri Oct 17, 2025 Assignment Binomial/proportions due by 11:59pm Mon Oct 20, 2025 Assignment Chi square 2 due by 1:30pm Fri Oct 24, 2025 Assignment Chi Square 3 due by 2pm Wed Nov 5, 2025 Assignment Experiment design due by 1:30pm Assignment crickets assignment due by 11:59pm Fri Nov 7, 2025 Quiz Take Home Exam due by 11:59pm Mon Nov 10, 2025 Assignment Chi square lab due by 11:59pm Fri Nov 21, 2025 Assignment Midterm 2 due by 3pm Mon Dec 1, 2025 Assignment Part 1 and 2 due by 11:59pm Assignment Part 3 due by 11:59pm Assignment Final Exam\
Assignment Final Grade\
Assignment In class assignment\
Assignment Midterm 1